install,_utils: add colour

diff --git a/install b/install
--- a/install
+++ b/install
@@ -36,7 +36,7 @@ function symlink {
     local name="$3"
 
     if [ ! -e "$target" ]; then
-        >&2 echo "$name: can't find target $target to symlink"
+        >&2 echo "$(error "$name"): can't find target $target to symlink"
         return 2
     fi
 
@@ -44,25 +44,25 @@ function symlink {
         existing_target=$(readlink -f "$link_name")
 
         if [ -e "$target" ] && [ "$existing_target" = "$target" ]; then
-            echo "$name already set correctly; skipping"
+            unimportant "$name already set correctly; skipping"
             return 0
         fi
 
         if [ -e "$target" ]; then
             if [ -e "$existing_target" ]; then
-                if confirm-action "WARN: '$link_name' is already a symlink, so did not make a link." \
-                                  "$name: '$link_name' already points to '$existing_target'; replace it?" \
+                if confirm-action "$(warn-pref "'$link_name' is already a symlink, so did not make a link.")" \
+                                  "$(warn "$name"): '$link_name' already points to '$existing_target'; replace it?" \
                                   y; then
-                    echo "replacing old $name"
+                    echo "replacing old $(info "$name")"
                     rm "$link_name"
                 else
                     return 1
                 fi
             else
-                if confirm-action "WARN: '$link_name' exists as a dead link; did not make a new link." \
-                                  "$name: '$link_name' exists as a dead link -- replace it?" \
+                if confirm-action "$(warn-pref "'$link_name' exists as a dead link; did not make a new link.")" \
+                                  "$(warn "$name"): '$link_name' exists as a dead link -- replace it?" \
                                   y; then
-                    echo "replacing dead link for $name"
+                    echo "replacing dead link for $(info "$name")"
                     rm "$link_name"
                 else
                     return 1
@@ -70,10 +70,10 @@ function symlink {
             fi
         fi
     elif [ -e "$link_name" ]; then
-        if confirm-action "WARN: '$link_name' already exists, so did not make a link." \
-                          "$name: a file at '$link_name' already exists; replace it?" \
+        if confirm-action "$(warn-pref "'$link_name' already exists, so did not make a link.")" \
+                          "$(warn "$name"): a file at '$link_name' already exists; replace it?" \
                           n; then
-            echo "replacing old $name"
+            echo "replacing old $(info "$name")"
             rm "$link_name"
         else
             return 1
@@ -100,7 +100,7 @@ function dotfile {
     return $?
 }
 
-echo symlinking dotfiles...
+title symlinking dotfiles...
 dotfile bashrc
 dotfile gdbinit
 dotfile gitconfig       "$(config-home)/git/config"
@@ -135,7 +135,7 @@ function install-script {
     return $res
 }
 
-echo symlinking scripts...
+title "symlinking scripts..."
 
 # install local scripts, if-present
 if [ -x "$d/local/install-scripts" ]; then
@@ -146,14 +146,14 @@ echo
 
 
 # === Symlinking other directories =====================================================
-echo symlinking other files...
+title symlinking other files...
 [ -e "$d/vim" ]       && symlink "$d/vim"       "$HOME/.vim/personal"       "vim personal dir"
 [ -e "$d/local/vim" ] && symlink "$d/local/vim" "$HOME/.vim/personal-local" "vim personal local dir"
 echo
 
 
 # === Other bits =======================================================================
-echo doing other misc stuff...
+title doing other misc stuff...
 
 # make directories for vim swapfiles & backups
 mkdir -p "$(state-home)/vim/backups"
@@ -163,7 +163,7 @@ mkdir -p "$(state-home)/vim/undo"
 # basic setup for vim plugin manager
 vim_plug_loc="$HOME/.vim/autoload/plug.vim"
 if [ -e "$vim_plug_loc" ]; then
-    echo "plug.vim already exists in $vim_plug_loc; skipping"
+    unimportant "plug.vim already exists in $vim_plug_loc; skipping"
 else
     curl -fLo "$vim_plug_loc" --create-dirs \
         https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
@@ -172,7 +172,7 @@ fi
 # setup tmux plugin manager
 tpm_dir="$(config-home)/tmux/plugins/tpm"
 if [ -e "$tpm_dir" ]; then
-    echo "tpm already exists in $tpm_dir; skipping"
+    unimportant "tpm already exists in $tpm_dir; skipping"
 else
     git clone https://github.com/tmux-plugins/tpm "$tpm_dir"
 fi
@@ -181,7 +181,7 @@ fi
 rustup_dir="$(data-home)/rustup"
 cargo_dir="$(data-home)/cargo"
 if [[ -e "$rustup_dir" && -e "$cargo_dir" ]]; then
-    echo "rustup & cargo already exist in $rustup_dir & $cargo_dir; skipping"
+    unimportant "rustup & cargo already exist in $rustup_dir & $cargo_dir; skipping"
 elif [ "$default_choice" != false ]; then
     if [ "$default_choice" = true ] ||
        yesno "do you want to install rust & cargo?"; then
@@ -193,14 +193,14 @@ fi
 
 # reminders for manual bits i've not automated yet
 echo
-echo DONE. remember to do these too:
+echo "$(info DONE). remember to do these too:"
 echo "* run :PluginInstall in vim to install plugins"
 echo "* run <prefix>+I in tmux to install plugins"
 echo "* do any machine-specific setup in local/{gitconfig,bash/*,vim/*} (then run again)"
 
 if [[ ! $(tmux -V) =~ "tmux 3" ]]; then
     echo
-    echo "WARN: your tmux is too old to understand \$XDG_CONFIG_HOME."
+    warn-pref "your tmux is too old to understand \$XDG_CONFIG_HOME."
     echo "      best thing is to make bash/local/tmux.bash, with this line:"
     echo
     echo 'alias tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"'
