+micromamba.bash;misc tweaks;utils,git,bash
micromamba.bash:

* basic setup for micromamba
* setup for being able to run binaries from the `global` environment
  like normal commands

utils: `exit-code` function, to echo given command's exit code to stdout

git: submodule-related config

bash: `rgp` alias for running rg only on python files

diff --git a/scripts/update-clangd b/scripts/update-clangd
--- a/scripts/update-clangd
+++ b/scripts/update-clangd
@@ -21,9 +21,7 @@ if echo "$info" | grep "$rate_limit_msg" >/dev/null 2>&1; then
 fi
 
 version="$(echo "$info" | grep "$json_version_tag" | sed 's/.*"'$json_version_tag'":\s*"\([0-9A-Za-z_\.]\+\)".*/\1/')"
-if have-cmd clangd; then
-    local_version="$(clangd --version | head -n 1 | sed 's/clangd version \([0-9\.]\+\) .*/\1/')"
-fi
+have-cmd clangd && local_version="$(clangd --version | head -n 1 | sed 's/clangd version \([0-9\.]\+\) .*/\1/')"
 
 if [ "$version" == "$local_version" ]; then
     info "latest version $version matches locally-installed version; not downloading."
@@ -36,9 +34,8 @@ filename="clangd-linux-$version"
 tmpdir=$(mktemp -d)
 
 url="https://github.com/$github_repo/releases/download/$version/$filename.zip"
-wget "$url" --directory-prefix="$tmpdir" -o "$tmpdir/wget_log"
-if [ $? -ne 0 ]; then
-    >&2 echo "error downloading package:"
+if ! wget "$url" --directory-prefix="$tmpdir" -o "$tmpdir/wget_log"; then
+    >&2 error "error downloading package:"
     >&2 cat "$tmpdir/wget_log"
     rm -r "$tmpdir"
     exit 1
@@ -48,9 +45,8 @@ fi
 mkdir -p "$destination"
 
 zip_file="$tmpdir/$filename.zip"
-unzip -q "$zip_file" -d "$tmpdir"
-if [ $? -ne 0 ]; then
-    >&2 echo "error unzipping package from $zip_file"
+if ! unzip -q "$zip_file" -d "$tmpdir"; then
+    >&2 error "error unzipping package from $zip_file"
     rm -r "$tmpdir"
     exit 1
 fi
diff --git a/scripts/update-vim b/scripts/update-vim
--- a/scripts/update-vim
+++ b/scripts/update-vim
@@ -5,7 +5,6 @@ source "$DOTFILES/bash/_utils.bash"
 d="$HOME/src/bin/vim"
 
 makefile_changed=0
-pull_return_code=0
 compile_needed=1
 reconfig_needed=0
 
@@ -18,23 +17,22 @@ if [ ! -d "$d" ]; then
     fi
 
     parent="$(dirname "$d")"
-    mkdir -p "$parent"
-    if [ "$?" != 0 ]; then
+    if ! mkdir -p "$parent"; then
         >&2 error "failed to create directory $parent for vim clone; exiting"
         exit 1
     fi
     cd "$parent"
 
-    git clone "https://github.com/vim/vim.git"
-    pull_return_code="$?"
+    if ! git clone "https://github.com/vim/vim.git"; then
+        >&2 error "git pull failed; not building" && exit 1
+    fi
     cd "$d"
 else
     # pull repo if present
     cd "$d"
 
     # check if makefile has been customised
-    git diff --exit-code "$d/src/Makefile" >/dev/null 2>&1
-    makefile_changed="$?"
+    makefile_changed="$(exit-code git diff --exit-code src/Makefile)"
     # not perfect logic as the unstash bumps the date, but good enough for our purposes?
     when_installed_changed="$(date -r src/Makefile +%s)"
 
@@ -46,12 +44,9 @@ else
     pull_return_code="$?"
     git stash pop
 
-    [ "$hash_before" == "$(git rev-parse HEAD)" ] && compile_needed=0
-fi
+    [ "$pull_return_code" != 0 ] && >&2 error "git pull failed; not rebuilding" && exit 1
 
-if [ "$pull_return_code" != 0 ]; then
-    >&2 error "git pull failed; not re-making"
-    exit "$pull_return_code"
+    [ "$hash_before" == "$(git rev-parse HEAD)" ] && compile_needed=0
 fi
 
 # apply makefile customisation if needed
