general cleanup; update-clangd: check existing ver

diff --git a/scripts/update-clangd b/scripts/update-clangd
--- a/scripts/update-clangd
+++ b/scripts/update-clangd
@@ -1,4 +1,6 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
+
+source "$DOTFILES/bash/_utils.bash"
 
 github_repo="clangd/clangd"
 destination="$HOME/src/bin"
@@ -8,17 +10,25 @@ json_version_tag="tag_name"
 
 info="$(curl -s -S https://api.github.com/repos/$github_repo/releases/latest)"
 if [ $? -ne 0 ]; then
-    >&2 echo error getting latest version info via curl.
+    >&2 error "error getting latest version info via curl."
     exit 1
 fi
 
 rate_limit_msg="API rate limit exceeded"
 if echo "$info" | grep "$rate_limit_msg" >/dev/null 2>&1; then
-    >&2 echo GitHub API rate limit exceeded.
+    >&2 error "GitHub API rate limit exceeded."
     exit 1
 fi
 
-version="$(echo $info | grep $json_version_tag | sed 's/.*"'$json_version_tag'":\s*"\([0-9A-Za-z_\.]\+\)".*/\1/')"
+version="$(echo "$info" | grep "$json_version_tag" | sed 's/.*"'$json_version_tag'":\s*"\([0-9A-Za-z_\.]\+\)".*/\1/')"
+if have-cmd clangd; then
+    local_version="$(clangd --version | head -n 1 | sed 's/clangd version \([0-9\.]\+\) .*/\1/')"
+fi
+
+if [ "$version" == "$local_version" ]; then
+    info "latest version $version matches locally-installed version; not downloading."
+    exit 0
+fi
 
 # download release to temp dir
 filename="clangd-linux-$version"
@@ -49,3 +59,9 @@ fi
 mv "$tmpdir/clangd_$version" "$destination/clangd"
 
 rm -r "$tmpdir"
+
+if [ -n "$local_version" ]; then
+    echo "updated $(info-col "$local_version") -> $(info-col "$version")"
+else
+    echo "installed clangd $(info-col "$version")"
+fi
diff --git a/scripts/update-vim b/scripts/update-vim
--- a/scripts/update-vim
+++ b/scripts/update-vim
@@ -11,7 +11,7 @@ compile_needed=1
 # get sources up-to-date
 if [ ! -d "$d" ]; then
     # clone repo if not present
-    if ! yesno "$(info-pref "vim not yet cloned; clone now?")"; then
+    if ! yesno "$(info "vim not yet cloned; clone now?")"; then
         echo did not clone.
         exit 0
     fi
@@ -19,7 +19,7 @@ if [ ! -d "$d" ]; then
     parent="$(dirname "$d")"
     mkdir -p "$parent"
     if [ "$?" != 0 ]; then
-        >&2 error-pref "failed to create directory $parent for vim clone; exiting"
+        >&2 error "failed to create directory $parent for vim clone; exiting"
         exit 1
     fi
     cd "$parent"
@@ -47,7 +47,7 @@ else
 fi
 
 if [ "$pull_return_code" != 0 ]; then
-    >&2 error-pref "git pull failed; not re-making"
+    >&2 error "git pull failed; not re-making"
     exit "$pull_return_code"
 fi
 
@@ -65,5 +65,5 @@ fi
 if [ "$compile_needed" == 1 ]; then
     make reconfig && make
 else
-    info-pref "already up-to-date; didn't rebuild"
+    info "already up-to-date; didn't rebuild"
 fi
